global using MediatR;
global using AutoMapper;
global using Application.Mapper;
global using Application.Queries;
global using Application.Responses;
global using Application.Commands;
global using Application.Handlers.QueryHandlers;
global using Application.Handlers.CommandHandlers;
global using Core.Repositories;